### ISSUE TITLE
Traffic-Cone 

### ISSUE THREAD

**Issue by brahami14** [jbehley/voxelizer#12]
Hello, 
Thank you for the great work you have done,
I have a question please in kitti semantic dataset do you have annotated cone or there is no cone in the data.
Thanks in advance

**Comment by jbehley** [comment]
you mean a "traffic cone" ? I think there is a sequence, where there is a traffic cone included, but it should be annotated as "other_object".

**Comment by brahami14** [comment]
yeah , "traffic cone" sorry, Thank you for your answer .

I have another question, please, did you annotated "construction vehicule", 

Thanks

**Comment by jbehley** [comment]
there was a crane and i think a construction site; these were either labeled as other_vehicle or other_object.

but note that the "other_xxx" classes are not considered in the evaluation. this was also caused by the low number of specific objects for these classes.
