### ISSUE TITLE
glow seems to be broken

### ISSUE THREAD

**Issue by Montyro** [jbehley/voxelizer#14]
Hi, I have been trying to compile the voxelizer and i got some errors about compile_shaders not being present. Seemingly latest push in glow makes catkin not find the dependency. 

For any user finding this issue, going back to the previous glow commit (inside glow folder after git clone do git checkout 66d7f855514baed8dca0d1b82d7a51151c9eef3 to roll it back) allowed me to do catkin build voxelizer.

**Comment by jbehley** [comment]
yes. I have to also update the other projects that use `glow`. I switched to a catkin-less build as it broke for SuMa and forgot about the other dependencies. (Same happens now also with semantic_suma). Sorry for the breaking changes.

I will refactor also this package such that it's possible to build without catkin and plain cmake. However, I'm not sure when this will happen.

**Comment by jbehley** [comment]
I update the repository. Now it should build again with cmake. (No need for catkin anymore.)

If you encounter further problems, let me know.
