### ISSUE TITLE
Broken Window Layout

### ISSUE THREAD

**Issue by leo-ashton** [jbehley/voxelizer#15]
First and foremost, I would like to extend my gratitude for your hard work on this project. It's helpful for my work, and I truly appreciate the effort that has gone into its development.

However, I've encountered an issue that I hope can be addressed. On my Ubuntu 20.04 system, the visualization window does not maintain its intended size and, more critically, the progress bar overlaps with the visualization window, which hampers usability.

![206cfdb3a7cc3252ce5b292c5c164f03](https://github.com/jbehley/voxelizer/assets/60648876/a3752828-07fd-4bd0-a817-beb21ac5a99f)

![2e58a6d7d0009f2da15b628de49b3773_720](https://github.com/jbehley/voxelizer/assets/60648876/9c2635de-554e-43b2-81bf-c5e0ce549548)

Here are the versions of the dependencies installed on my system, which might be relevant to this issue:

- **Eigen3**: `3.3.7-2`
- **Boost**: `1.71.0.0ubuntu2`
- **Qt**: `5.12.8` (QMake version 3.1)

I believe this information might be useful for diagnosing the problem. Please let me know if there's any additional information I can provide or any potential workarounds I could try in the meantime.

Thank you once again for your dedication to this project, and I look forward to any updates regarding this issue.

**Comment by jbehley** [comment]
A little bit delay, sorry. However, I found the problem and could fix the layout issue. 

Let me know if this resolves your issue.

**Comment by leo-ashton** [comment]
Apologize for the delayed response. Thank you for your great work, the window layout seems to be back to normal! 

I will be closing this issue.

**Comment by wjq777777** [comment]
@leo-ashton 
Hello, we have also been paying attention to this voxelization tool recently. May I ask if you have solved it?
When we execute the./gen_data program in the terminal, "1 point clouds read" keeps appearing. Is this normal? At present, the voxels folder under my dataset/sequences/00000 file has not generated any voxel files.
Could you help me solve this problem?
Looking forward to your reply
