### ISSUE TITLE
Query about the settings of the voxelizer

### ISSUE THREAD

**Issue by JoyHighmore** [jbehley/voxelizer#7]
Thanks for you brilliant work! 

I have several things unclear and could you please give me more details?

1.  as said in the paper, the max range of the point cloud is 50, but we could still adjust the value larger, like 70 as default. What's that for?
2. When increasing the number for prior scans (future scans), the denser the point cloud is, are you using the SLAM to reconstruct it? What's the maximun value for prior scans and past cans? How do you make sure that there is always at least 50 overlap region within?
3. For the past cans, I've noticed that the loweset value I could try is 1. Is that meaning the current scan only or the current scan with the previous one?
4. How can we generate the denser point cloud data using this tool or any availble tools?

Best,
JH

**Comment by jbehley** [comment]
thanks for your interest in our work.

1. We labeled only point clouds in the range up to 50 m. But the point clouds have also points at a larger range. We found that the noise introduced by faraway points in the aggregated point cloud to large. Therefore, we only used points up to 50m to aggregate point clouds for labeling.
2. We used poses estimated with our SLAM pipeline (http://www.roboticsproceedings.org/rss14/p16.pdf) as we also needed poses for the test set. Additionally, SuMa made it possible to account for loop closures, which simplified the annotation process. Nowadays, there are many more excellent LIDAR SLAM pipelines available that achieve even higher accuracy and maybe even better consistency of the aggregated scans. (e.g. [CT ICP](https://arxiv.org/abs/2109.12979) or the different LOAM variants). We used the configuration: https://github.com/jbehley/voxelizer/blob/master/assets/semantic_kitti.cfg (I do not really remember the whole process as also Martin took mostly care of this part...I just wrote mainly the voxelizer.)
3. I think when you look in the code, then the current scan is inside the "prior scans" and the "past scans" are from t=idx + 1...I know the naming is not perfect. https://github.com/jbehley/voxelizer/blob/0ace074b8981ded4c9bb73ad362b44ae2e57ad34/src/widget/KittiReader.cpp#L56-L143
4. I think Andres had some code for the multi-scan case, which you could use as a basis: https://github.com/PRBonn/semantic-kitti-api/blob/master/generate_sequential.py. But essentially, you just have to multiply all the scans with the poses (Beware: To have it consistent with the KITTI format, we have all LiDAR poses in the coordinate system of the left(?) camera. Therefore, one needs to pre/post-multiply the calibration matrices to get "real" LiDAR poses: https://github.com/PRBonn/semantic-kitti-api/blob/4b30094b9368ddf86dc2e994db276fb6aaddf69a/generate_sequential.py#L42-L68

**Comment by JoyHighmore** [comment]
@jbehley Thank you so much for the response. There is one more question about the .cfg. So I ran the code "./gen_data ../assests/semantic_kitti_dense.cfg path/to/sequence/00 path/to/sequence/voxels" but got the voxels with resolution of [80,80,6], It seems the code didn't follow the settings in the .cfg file (which should be [256,256,32]) but followed the voxel initialize?

**Comment by jbehley** [comment]
hmmm, that's strange; since I generated this data here: http://www.semantic-kitti.org/assets/data_odometry_voxels_all.zip using these settings.

**Comment by wjq777777** [comment]
@JoyHighmore 
Hello, we have also been paying attention to this voxelization tool recently. May I ask if you have solved it?
When we execute the./gen_data program in the terminal, "1 point clouds read" keeps appearing. Is this normal? At present, the voxels folder under my dataset/sequences/00000 file has not generated any voxel files.
Could you help me solve this problem?
Looking forward to your reply

**Comment by jbehley** [comment]
Please open a new issue with the exact steps that you conducted. It is currently hard to diagnose the problem without more detailed information.
